name: Deploy Frontend

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 9011
          script: |
            cd ~/judge/judge-frontend || exit 1
            git pull origin main
            docker-compose stop frontend
            docker-compose rm -f frontend
            docker-compose up -d --build frontend
